### ISSUE TITLE
register opengl buffer failed

### ISSUE THREAD

**Issue by HK-SHAO** [chenyongxing/KDRay#1]
我先是运行 `cmake .` 得到报错，无法找到 LibGL 在 `viewer\CMakeLists.txt:14` 

```cmake
find_library(libGL opengl32 REQUIRED)
```

然后将 `C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22000.0\um\x64` 的 `opengl32.lib` 加入了系统环境变量就可以了

用 `Microsoft Visual Studio Community 2022 (64 位) ` 正常编译，Debug 版和 Release 版本打开后

程序看起来是正常运行的，但是终端提示

```bash
[2023-03-23 12:11:08.469] [kdRay] [critical] register opengl buffer failed. OS call failed or operation not supported on this OS
```

窗口右边的 viewport 没有显示，加载进入一个场景后也是空的，没有显示。并且会再次提示上面的错误

`kdray\framebuffer.cpp:59`

- update: 运行 https://github.com/chenyongxing/KDRay/releases/tag/release 也是这种情况

**Comment by HK-SHAO** [comment]
在确保程序运行在独立显卡之后，就没有这个报错了。
如果是笔记本的话，最好是切换到独显直连

**Comment by chenyongxing** [comment]
cuda和opengl互交互问题。gl buffer无法给cuda使用。推测opengl跑在集显。cuda在N卡上

**Comment by HITzihao** [comment]
我也遇到了这个问题，请问如何解决呢？
